### PR TITLE
Reduce verbosity in output

### PR DESCRIPTION
**Pull request by arzola**
I think the progress and the tons of warnings are not useful for pipelines

image

### CODE REVIEW

**Comment by nelsonamaya82** [comment]
I think the progress and warnings logs are useful to identify possible issues in the build/deployment process. Maybe we should take care of warnings too (not only errors) to avoid the logs printing all those warnings, but would like to have some feedback from the other reviewers.

**Comment by arzola** [comment]
They are useful when we take care of them, but to be honest I haven't see any Nolte project that fixed those issues, the PHP ones are the less verbose but if you look at the verbosity of the SASS or CSS linters you'll see there are a lot of things that are not solvable in the real world

image

**Comment by adamf321** [comment]
I think we need to fix these or update the lint rules. it doesn't make sense to just ignore them.

**Comment by nelsonamaya82** [comment]
Also to fix all those warnings we could use an auto-fixer when running the linter (similar to phpcbf), maybe there's a  `--fix` option to automatically resolve lint errors/warnings. Anyway for new projects we'll get rid of this as we are using Tailwind.

**Pull request closed without merging**
